#!/usr/bin/env bun
/**
 * Generate commands barrel file
 *
 * Auto-discovers all command files in src/cli/commands/ and generates
 * the barrel export file (index.ts). Run before build.
 */

import { readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const COMMANDS_DIR = join(import.meta.dir, "../src/cli/commands");
const OUTPUT_FILE = join(COMMANDS_DIR, "index.ts");

const files = readdirSync(COMMANDS_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".test.ts") && !f.endsWith(".spec.ts"))
  .sort();

const exports = files
  .map(f => `export * from "./${f.replace(".ts", ".js")}";`)
  .join("\n");

const content = `/**
 * Commands Barrel Export (auto-generated)
 *
 * DO NOT EDIT - This file is generated by scripts/gen-commands.ts
 * Run: bun run gen:commands
 */

${exports}
`;

writeFileSync(OUTPUT_FILE, content);
console.log(`Generated ${relative(process.cwd(), OUTPUT_FILE)} with ${files.length} command files`);
